// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtovmknldanpipgddsrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0b3Zta25sZGFucGlwZ2Rkc3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODIyNjYsImV4cCI6MjA2NTg1ODI2Nn0.S2Nr8XrHmFkDlI_LrUrXhA_2h4qczAQ1nb6EE8sDC5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});